name: TOC Generator
on:
  push:
    branches: [ main, master ]
    paths: [ 'README.md' ]

jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TOC Generator
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: README.md
          TOC_TITLE: "## Table of Contents"